#pragma once
#pragma warning(disable: 4018 4221 4244 4267 4288 4302 4305 4309 4311 4312 4733 4838 4996)

#define DETOURS_INTERNAL
#define assert(a) static_assert(a, "Assertion failed")
#define DIRECTINPUT_VERSION 0x0800
#include <Windows.h>
#include <direct.h>
#include <string>
#include <regex>
#include <bit>
#include <type_traits>
#include <initializer_list>
#include <intrin.h>
#include <immintrin.h>
#include <CommCtrl.h>
#include <vector>
#include <stack>
#include <map>
#include <unordered_map>
#include <sstream>
#include <fstream>
#include <algorithm>
#include <d3d9.h>
#pragma comment (lib, "d3dx9.lib")
#include <d3dx9math.h>
#include <dinput.h>
#include <dsound.h>

class DetectorWindow;
class INISettingCollection;
class ModInfo;
class Actor;
class ActorAnimData;
class MagicItem;
class MagicTarget;
class CombatController;
class SpellItem;
class EffectNode;
class DialoguePackage;
class BirthSign;
class AlchemyItem;
class ActiveEffect;
class ModelKF;
class Creature;
class SkinInfo;
class BoundObjectListHead;
class Character;
class WaterManager;
class WaterPlaneData;
class Script;
class EnchantmentItem;
class ScriptEventList;
class Menu;
class InventoryMenu;
class Tile;
class TileText;
class Projectile;
class MediaSet;
class MediaLocationController;

class TESSaveLoadGame;
class TESForm;
class TESObjectREFR;
class TESObjectCELL;
class TESObjectBOOK;
class TESObjectARMO;
class TESObjectANIO;
class TESObjectLAND;
class TESObjectACTI;
class TESObjectCONT;
class TESObjectDOOR;
class TESObjectMISC;
class TESObjectSTAT;
class TESObjectTREE;
class TESObjectARMA;
class TESFlora;
class TESFurniture;
class TESAmmo;
class TESPathGrid;
class TESTopic;
class TESTopicInfo;
class TESRegion;
class TESRegionList;
class TESClass;
class TESNPC;
class TESSound;
class TESHair;
class TESEyes;
class TESRace;
class TESLandTexture;
class TESFaction;
class TESCombatStyle;
class TESLoadScreen;
class TESEffectShader;
class TESRegionDataManager;
class TESPackageData;
class TESChildCell;
class TESImageSpace;
class TESImageSpaceModifier;
class TESReputation;
class TESChallenge;
class TESRecipe;
class TESRecipeCategory;
class TESAmmoEffect;
class TESCasino;
class TESCaravanDeck;
class TESLoadScreenType;
class TESGrass;
class TESLevCharacter;
class TESKey;
class TESLevSpell;
class TESShout;
class TESWordOfPower;
class TESSoulGem;
class TESLevItem;
class TESObjectLIGH;
class BSExtraData;
class ExtraCount;
struct BaseExtraList;
struct ExtraDataList;
struct NPCPerksInfo;
class TESGlobal;

class BSBound;
class BSFogProperty;
class BSRenderedTexture;
class BSTempNodeManager;
class BSAnimGroupSequence;
class BSFile;
class BSGameSound;
class BSSoundInfo;
struct AnimData;
struct BipedAnim;

class BGSHeadPart;
class BGSEncounterZone;
class BGSCameraShot;
class BGSAcousticSpace;
class BGSRagdoll;
class BGSVoiceType;
class BGSImpactData;
class BGSImpactDataSet;
class BGSProjectile;
class BGSExplosion;
class BGSRadiationStage;
class BGSDehydrationStage;
class BGSHungerStage;
class BGSSleepDeprivationStage;
class BGSDebris;
class BGSBodyPartData;
class BGSNote;
class BGSListForm;
class BGSMenuIcon;
class BGSMessage;
class BGSLightingTemplate;
class BGSMusicType;
class BGSAddonNode;
class BGSKeyword;
class BGSLocationRefType;
class BGSAction;
class BGSTextureSet;
class BGSTalkingActivator;
class BGSApparatus;
class BGSEquipSlot;
class BGSRelationship;
class BGSScene;
class BGSAssociationType;
class BGSOutfit;
class BGSArtObject;
class BGSMaterialObject;
class BGSMovementType;
class BGSSoundDescriptorForm;
class BGSDualCastData;
class BGSSoundCategory;
class BGSSoundOutput;
class BGSCollisionLayer;
class BGSColorForm;
class BGSReverbParameters;
class BGSFootstep;
class BGSFootstepSet;
class BGSStoryManagerBranchNode;
class BGSStoryManagerQuestNode;
class BGSStoryManagerEventNode;
class BGSDialogueBranch;
class BGSMusicTrackFormWrapper;
class BGSCameraPath;
class BGSMaterialType;
class BGSLocation;
class BGSConstructibleObject;
class BGSHazard;
class BGSShaderParticleGeometryData;
class BGSReferenceEffect;
class BGSMovableStatic;
class BGSStaticCollection;
class BGSIdleMarker;
class BGSSkillPerkTreeNode;
class NiNode;
class NiPick;
class NiTextKeyExtraData;
class NiFormArray;
class NiStringPalette;
class NiStream;
class NiTimeController;
class NiPropertyState;
class NiDynamicEffectState;
class NiProperty;
class NiFogProperty;
class NiAlphaProperty;
class NiCullingProperty;
class NiStencilProperty;
class NiMaterialProperty;
class NiTexturingProperty;
class NiCullingProcess;
class NiDynamicEffect;
class NiControllerManager;
class NiVisibleArray;
class NiAdditionalGeometryData;
class NiGeometryData;
class NiTriBasedGeomData;
class NiTriStripsData;
class NiTriShapeData;
class NiGeometryGroup;
class NiRenderedCubeMap;
class NiTexture;
class NiGeometry;
class NiTriBasedGeom;
class NiTriShape;
class NiTriStrips;
class NiPixelData;
class NiParticles;
class NiLines;
class NiGeometryGroupManager;
class NiScreenElements;
class NiSourceCubeMap;
class NiRenderer;
class Ni2DBuffer;
class NiD3DRenderStateGroup;
class NiD3DShaderProgram;
class NiD3DShader;
class NiDX9LightManager;
class NiDX9VertexBufferManager;
class NiDX9ShaderConstantManager;
class NiDX9IndexBufferManager;
class NiDX9TextureManager;
class NiDX9RenderedTextureData;
class NiDX9RenderedCubeMapData;
class NiDX9DynamicTextureData;
class NiDX9AdapterDesc;
class NiDX9DeviceDesc;
class NiDX9Renderer;
class NiDX9RenderState;
class NiDX92DBufferData;
class NiCollisionObject;
class bhkNiCollisionObject;
class bhkCollisionObject;
class bhkPCollisionObject;
class bhkSPCollisionObject;
class bhkBlendCollisionObject;
class bhkPhantom;
class bhkAabbPhantom;
class bhkShapePhantom;
class LightingData;
struct NiObjectCopyInfo;
struct Sound;
class BSRenderPassList;
class NiExtraData;

class BSShaderAccumulator;
class BSFadeNode;
class BSMultiBoundNode;
class BSSegmentedTriShape;
class BSResizableTriShape;
class BSShaderTextureSet;
class EffectShaderProperty;
class TileShaderProperty;
struct BSRenderPass;
class BSPortalGraph;
class BSShaderProperty;
class BSMultiBound;
class NiCamera;

class BSPortal;

class ShadowSceneLight;
class AnimSequenceBase;

class TESObjectREFR;
class TESWaterCullingProcess;

class bhkRigidBody;
class bhkCollisionObject;
class bhkBlendCollisionObject;
class bhkLimitedHingeConstraint;

class ImageSpaceManager;
class ImageSpaceEffectParam;
class ImageSpaceShaderParam;
class NiAVObject;


struct NiPoint2;
struct NiVector3;
struct NiVector4;
struct NiQuaternion;
struct NiMatrix33;
struct NiTransform;
#include "../lib/Detours/detours.h"
#include "../lib/Nvidia/nvapi.h"
#include "../lib/Bink/bink.h"
#include "../Base/Logger.h"
#include "../Base/Types.h"
#include "../Base/SafeWrite.h"
#include "../Base/PluginVersion.h"
#include "..//Base/Utils.h"
#include "Plugin.h"
#include "../NewVegas/nvse/DataTypes.h"
#include "../NewVegas/nvse/GameNi.h"
#include "../NewVegas/nvse/GameHavok.h"
#include "../NewVegas/nvse/Game.h"
#include "Defines.h"
#include "Base.h"
#include "Managers.h"
#include "../Core/Hooks/GameCommon.h"
#include "../Core/Hooks/FormsCommon.h"
#include "../NewVegas/Hooks/Settings.h"
#include "../NewVegas/Hooks/Game.h"
#include "../NewVegas/Hooks/ShaderIO.h"
#include "../NewVegas/Hooks/Render.h"
#include "../NewVegas/Hooks/Shadows.h"
#include "../NewVegas/Hooks/FlyCam.h"
